// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package kinesisiface_test

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/volker48/c2k/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/kinesis"
	"github.com/volker48/c2k/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/kinesis/kinesisiface"
)

func TestInterface(t *testing.T) {
	assert.Implements(t, (*kinesisiface.KinesisAPI)(nil), kinesis.New(nil))
}
